In [4]:
import pandas as pd

orb_range_time = "10:00"
DATA_PATH = "D:/FM/ALGOTRADING/artifacts/backtest/hist_data_5.json"

data = pd.read_json(DATA_PATH)

# Normalize date/time
data["date"] = pd.to_datetime(data["date"]).dt.date
data["time"] = pd.to_datetime(data["time"].astype(str)).dt.time

orb_start = pd.to_datetime("09:15").time()
orb_end = pd.to_datetime(orb_range_time).time()

# ORB window
orb = data[
    (data["time"] >= orb_start) &
    (data["time"] < orb_end)
]

# Calculate ORB separately for EACH symbol on EACH day
orb_daily = (
    orb.groupby(["date", "symbol"])
       .agg(
           orb_high=("high", "max"),
           orb_low=("low", "min")
       )
       .reset_index()
)

orb_daily["orb_range"] = (
    orb_daily["orb_high"] - orb_daily["orb_low"]
)

# Merge back using BOTH date and symbol
data = data.merge(
    orb_daily,
    on=["date", "symbol"],
    how="left"
)

data

C:\Users\hp\AppData\Local\Temp\ipykernel_27436\164182918.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data["time"] = pd.to_datetime(data["time"].astype(str)).dt.time

,date,time,open,high,low,close,volume,symbol,orb_high,orb_low,orb_range
0,2022-01-03,09:15:00,125.40,125.40,124.70,125.35,368526,NTPC,125.95,124.7,1.25
1,2022-01-03,09:20:00,125.40,125.75,125.15,125.60,254040,NTPC,125.95,124.7,1.25
2,2022-01-03,09:25:00,125.55,125.70,125.45,125.70,144340,NTPC,125.95,124.7,1.25
3,2022-01-03,09:30:00,125.75,125.95,125.60,125.70,196599,NTPC,125.95,124.7,1.25
4,2022-01-03,09:35:00,125.65,125.90,125.55,125.70,173600,NTPC,125.95,124.7,1.25
...,...,...,...,...,...,...,...,...,...,...,...
350763,2026-09-24,15:05:00,394.60,394.65,393.30,393.50,228886,BEL,396.75,393.9,2.85
350764,2026-09-24,15:10:00,393.50,393.50,393.00,393.25,185761,BEL,396.75,393.9,2.85
350765,2026-09-24,15:15:00,393.30,393.30,393.30,393.30,99,BEL,396.75,393.9,2.85
350766,2026-09-24,15:20:00,393.30,393.30,393.30,393.30,0,BEL,396.75,393.9,2.85
350767,2026-09-24,15:25:00,392.00,392.00,392.00,392.00,187376,BEL,396.75,393.9,2.85

In [ ]:
#charges

df=pd.read_csv(r"D:\FM\ALGOTRADING\artifacts\backtest_reports\ORBStrategy\20260925-235204\trades.csv")
df['charges']=35
df['final_pnl']=df['pnl']-df['charges']

In [27]:
df['pnl'].sum()

np.float64(111572.25000000015)

In [28]:
df['charges'].sum()

np.int64(220770)

In [29]:
df['final_pnl'].sum()

np.float64(-109197.74999999985)

In [30]:
df.tail()

,symbol,trading_date,direction,orb_high,orb_low,orb_range,entry_timestamp,entry_date,entry,sl,...,equity_before,equity_after,gross_pnl,transaction_cost,pnl,pnl_percent,holding_period,is_closed,charges,final_pnl
7354,BEL,2026-09-24,LONG,396.75,393.90,2.85,2026-09-24 11:20:00,2026-09-24 11:20:00,397.1,394.25,...,212264.35,211163.20,-379.05,0.0,-379.05,-0.717703,0,True,30,-409.05
7355,ETERNAL,2026-09-24,SHORT,341.50,338.20,3.30,2026-09-24 13:50:00,2026-09-24 13:50:00,337.9,341.20,...,211542.25,211678.00,514.80,0.0,514.80,0.976620,0,True,30,484.80
7356,BEL,2026-09-24,SHORT,396.75,393.90,2.85,2026-09-24 14:10:00,2026-09-24 14:10:00,393.5,396.35,...,211163.20,211530.60,-147.40,0.0,-147.40,-0.279543,0,True,30,-177.40
7357,NTPC,2026-09-24,SHORT,327.00,325.70,1.30,2026-09-24 13:45:00,2026-09-24 13:45:00,325.4,326.70,...,211542.25,211522.50,-8.10,0.0,-8.10,-0.015366,0,True,30,-38.10
7358,VEDL,2026-09-24,SHORT,269.40,265.65,3.75,2026-09-24 13:40:00,2026-09-24 13:40:00,265.4,269.15,...,211542.25,211572.25,49.75,0.0,49.75,0.094197,0,True,30,19.75